name:                jlint
version:             0.1.0.0
github:              "hsfl-pltp/jlint"
license:             BSD3
author:              "Jan Christiansen"
maintainer:          "jan.christiansen@hs-flensburg.de"
copyright:           "2022 Jan Christiansen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/jlint#readme>

dependencies:
- aeson
- base
- bytestring
- containers
- directory
- filepath
- filemanip
- HaXml
- language-java
- mtl
- optparse-applicative
- parsec
- process
- regex
- split
- text
- uniplate


library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wno-name-shadowing

executables:
  jlint:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jlint

tests:
  jlint-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jlint
    - filepath
    - HUnit
    - split
