name: jlint
version: 0.1.0.0
github: "githubuser/jlint"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2022 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/jlint#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers ^>=0.6.4.1
  - optparse-applicative >= 0.16.1.0 && < 1
  - language-java >= 0.2.9 && < 3
  - aeson >= 2.0.3 && < 2.1
  - bytestring >= 0.10.12.1 && < 0.11
  - uniplate >=1.6.11 && <1.7
  - mtl >= 2.2.2 && < 2.3
  - regex >= 1.1.0 && < 1.2
  - filemanip >= 0.3.6.3 && < 0.4
  - parsec >= 3.1.14.0 && < 3.2
  - HaXml ^>=1.25.9
  - process >= 1
  - text >= 1.2.5

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wno-name-shadowing

executables:
  jlint:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - jlint

tests:
  jlint-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - jlint
      - HUnit >= 1.6.2.0 && < 2
      - unliftio >= 0.2.21.0 && < 1
      - directory >= 1.3.6.2 && < 2
      - split >= 0.2.3.4 && < 0.3
      - parsec >= 3.1.14.0 && < 3.2
      - filepath >= 1.4.2.1 && < 1.5
      - MissingH >= 1.5.0.1 && < 1.6
