name: Haskell Format (Ormolu)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 ormolu-action:
   runs-on: self-hosted

   steps:
   - name: Checkout current repository
     uses: actions/checkout@v5

   - name: Ormolu Check Format
     uses: mrkkrp/ormolu-action@v6
